#!/usr/bin/env bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# If we fail, we want to fail royally
set -e

PARAMETERS="$(KPopTwist_ "$@")"
if [[ "$PARAMETERS" == "" ]]; then
  exit 1
fi
# We parse the parameters returned by KPopTwist_
OLD_IFS="$IFS"
IFS=$'\x1'
read -r PREFIX_IN KMERS_KEEP KMERS_SAMPLE THRESHOLD_KMERS PREFIX_OUT PREFIX_OUT_KMERS THREADS TEMPORARIES VERBOSE <<< "$PARAMETERS"
IFS="$OLD_IFS"

function conditional_echo {
  if [[ "$VERBOSE" == "true" ]]; then
    echo "$1"
  fi
}

# We generate and split the plain text table, so that R can import it
conditional_echo "$(date +"%c"): [1/16] Exporting table..."
TMPDIR=$(mktemp -d -p . KPopTwist-XXXXXXXXXX)
KPopCountDB -T "$THREADS" -i "$PREFIX_IN" -O "${TMPDIR}/TABLE"

export R_DATATABLE_NUM_PROCS_PERCENT=100
#export R_DATATABLE_THROTTLE=1000000

Rscript --vanilla <(
cat <<'_____'
  library(data.table)
  library(ca)
  #
  args<-commandArgs(trailingOnly=TRUE)
  output<-args[2]
  output_kmers<-args[3]
  keep<-args[4]
  if (is.na(args[5])||args[5]=="")
    args[5]<-"1."
  fraction<-as.numeric(args[5])
  threshold<-as.numeric(args[6])
  threads<-as.integer(args[7]) # Not really used at the moment
  temporaries<-as.logical(args[8]) # Not really used at the moment
  verbose<-as.logical(args[9])
  #
  conditional_echo<-function(s){
    if (verbose)
      cat(format(Sys.time(),paste0("%c: ",s,"...\n")))
  }
  conditional_echo("[2/16] Reading table")
  stuff<-data.table::fread(args[1],sep="\t",header=TRUE)
  conditional_echo("[3/16] Splitting table")
  kmers<-as.vector(stuff[,1])$V1
  stuff<-stuff[,-1]
  conditional_echo("[4/16] Discarding k-mers")
  if (keep!="") {
    idx_kmers<-1:length(kmers)
    names(idx_kmers)<-kmers
    keep<-t(data.table::fread(keep,sep="\t",header=FALSE))
    kmers<-keep
    stuff<-stuff[idx_kmers[keep],]
  }
  conditional_echo("[5/16] Resampling k-mers")
  sampled<-sort(sample(nrow(stuff),as.integer(nrow(stuff)*fraction)))
  kmers<-kmers[sampled]
  stuff<-stuff[sampled,]
  conditional_echo("[6/16] Thresholding k-mers")
  rsums<-rowSums(stuff)
  sampled<-which(rsums>=(max(rsums)*threshold))
  kmers<-kmers[sampled]
  stuff<-stuff[sampled,]
  conditional_echo("[7/16] Normalizing counts")
  stuff<-stuff[,lapply(.SD,function(col) col/sum(col))]
  conditional_echo("[8/16] Twisting counts")
  stuff_ca<-ca(stuff)
  conditional_echo("[9/16] Writing twisted")
  coords<-cacoord(stuff_ca,cols=TRUE)
  dnames<-colnames(coords)
  data.table::fwrite(as.data.table(coords,keep.rownames=TRUE),paste0(output,".KPopTwisted.txt"),quote=TRUE,sep="\t",buffMB=64)
  koords<-as.data.table(cacoord(stuff_ca,rows=TRUE))
  rownames(koords)<-kmers
  if (output_kmers!="")
    data.table::fwrite(koords,paste0(output_kmers,".KPopTwisted.txt"),row.names=TRUE,quote=TRUE,sep="\t",buffMB=64)
  conditional_echo("[10/16] Writing inertia")
  inertia<-t(stuff_ca$sv^2)
  colnames(inertia)<-dnames
  rownames(inertia)<-c("inertia")
  data.table::fwrite(as.data.table(inertia,keep.rownames=TRUE),paste0(output,".KPopInertia.txt"),quote=TRUE,sep="\t",buffMB=64)
  conditional_echo("[11/16] Normalizing twister")
  twister<-koords[,Map("/",.SD,stuff_ca$sv)]
  conditional_echo("[12/16] Transposing twister")
  twister<-data.table::transpose(twister)
  colnames(twister)<-kmers
  rownames(twister)<-dnames
  conditional_echo("[13/16] Writing twister")
  data.table::fwrite(twister,paste0(output,".KPopTwister.txt"),row.names=TRUE,quote=TRUE,sep="\t",buffMB=64)
_____
) "${TMPDIR}/TABLE.KPopKmerMat.txt" \
  "$PREFIX_OUT" "$PREFIX_OUT_KMERS" "$KMERS_KEEP" "$KMERS_SAMPLE" "$THRESHOLD_KMERS" \
  "$THREADS" "$TEMPORARIES" "$VERBOSE" 2> "${TMPDIR}/LOGGO.txt"

# We convert the results to binary form and remove temporary files
conditional_echo "$(date +"%c"): [14/16] Encoding twisted..."
KPopTwistDB -T "$THREADS" -I t "$PREFIX_OUT" -o t "$PREFIX_OUT" > "${TMPDIR}/LOGGO.txt" 2>&1
if [[ "$PREFIX_OUT_KMERS" != "" ]]; then
  KPopTwistDB -T "$THREADS" -I t "$PREFIX_OUT_KMERS" -o t "$PREFIX_OUT_KMERS" > "${TMPDIR}/LOGGO.txt" 2>&1
fi
conditional_echo "$(date +"%c"): [15/16] Encoding twister..."
KPopTwistDB -T "$THREADS" -I T "$PREFIX_OUT" -o T "$PREFIX_OUT" > "${TMPDIR}/LOGGO.txt" 2>&1
conditional_echo "$(date +"%c"): [16/16] Cleaning up..."
if [[ "$TEMPORARIES" == "false" ]]; then
  rm "${TMPDIR}/TABLE.KPopKmerMat.txt" "${TMPDIR}/TABLE.KPopMetaMat.txt" "${TMPDIR}/LOGGO.txt"
  rmdir "${TMPDIR}"
  rm "${PREFIX_OUT}.KPopTwisted.txt" "${PREFIX_OUT}.KPopInertia.txt" "${PREFIX_OUT}.KPopTwister.txt"
  if [[ "$PREFIX_OUT_KMERS" != "" ]]; then
    rm "${PREFIX_OUT_KMERS}.KPopTwisted.txt"
  fi
fi

conditional_echo "$(date +"%c"): All done."

